env:
  global:
language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database Hermione_test;' -U postgres
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
script:
  - bundle exec rspec
after_script:

