env:
  global:
language: ruby
rvm:
  - 2.4.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
script:
  - bundle exec rspec
after_script:

